In [4]:
import numpy as np
n=int(input("Enter number of unknown"))
col=[]
for i in range(0,n):
    row = []
    for j in range(0,n+1):
        print("Enter A",i,j)
        temp=float(input())
        row.append(temp)
    col.append(row)
A=np.matrix(col)
print(A)

input()
for i in range(0,n):
    for j in range(i+1,n):
        factor=A[j,i]/A[i,i]
        for k in range(0,n+1):
                        A[j,k]=A[j,k]-factor*A[i,k]
print(A)
x=np.zeros(n)
x[n-1]=(A[n-1,n]/A[n-1,n-1])
for i in range(n-2,-1,-1):
    sum=0
    for j in range(i+1,n):
        sum+=A[i,j]*x[i]
        x[i]=(A[i,n]-sum)/A[i,i]
print(x)
    

Enter number of unknown2
Enter A 0 0
7
Enter A 0 1
7
Enter A 0 2
9
Enter A 1 0
3
Enter A 1 1
3
Enter A 1 2
6
[[7. 7. 9.]
 [3. 3. 6.]]
9
[[7.         7.         9.        ]
 [0.         0.         2.14285714]]
[1.28571429        inf]


C:\Users\Amna Siddiqui\Anaconda3\lib\site-packages\ipykernel_launcher.py:22: RuntimeWarning: divide by zero encountered in double_scalars


#### 